title: LoremIpsum.js
description: A Node.js and Component.js module for generating lorem ipsum placeholder text
google_analytics: UA-33637708-3
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
